In [125]:
import pandas as pd
import numpy as np

In [126]:
credits=pd.read_csv("tmdb_5000_credits.csv")
movies=pd.read_csv('tmdb_5000_movies.csv')

In [127]:
credits.head()

,movie_id,title,cast,crew
0,19995,Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [128]:
movies.head()

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2007-05-19,961000000,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bondâ€™s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...","[{""iso_3166_1"": ""GB"", ""name"": ""United Kingdom""...",2015-10-26,880674609,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466
3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",http://www.thedarkknightrises.com/,49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-07-16,1084939099,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106
4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://movies.disney.com/john-carter,49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-03-07,284139100,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124

In [129]:
credits.shape

(4803, 4)

In [130]:
movies.shape

(4803, 20)

In [131]:
#id in both the cases are same so just merge them

In [132]:
credit_colunm_rename=credits.rename(index=str,columns={'movie_id':'id'})
merge_movies=movies.merge(credit_colunm_rename,on ='id')
merge_movies.head()

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,...,runtime,spoken_languages,status,tagline,title_x,vote_average,vote_count,title_y,cast,crew
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...",...,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800,Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...",...,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500,Pirates of the Caribbean: At World's End,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bondâ€™s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...",...,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466,Spectre,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",http://www.thedarkknightrises.com/,49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...",...,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106,The Dark Knight Rises,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://movies.disney.com/john-carter,49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]",...,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124,John Carter,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [133]:
movies=merge_movies.drop(['homepage','crew','title_x', 'title_y', 'status','production_countries'],axis='columns')
movies.head()

,budget,genres,id,keywords,original_language,original_title,overview,popularity,production_companies,release_date,revenue,runtime,spoken_languages,tagline,vote_average,vote_count,cast
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...",2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Enter the World of Pandora.,7.2,11800,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""..."
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...",2007-05-19,961000000,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]","At the end of the world, the adventure begins.",6.9,4500,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa..."
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bondâ€™s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...",2015-10-26,880674609,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",A Plan No One Escapes,6.3,4466,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr..."
3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...",2012-07-16,1084939099,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",The Legend Ends,7.6,9106,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba..."
4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]",2012-03-07,284139100,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]","Lost in our world, found in another.",6.1,2124,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c..."

In [134]:
movies.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4803 entries, 0 to 4802
Data columns (total 17 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   budget                4803 non-null   int64
 1   genres                4803 non-null   object
 2   id                    4803 non-null   int64
 3   keywords              4803 non-null   object
 4   original_language     4803 non-null   object
 5   original_title        4803 non-null   object
 6   overview              4800 non-null   object
 7   popularity            4803 non-null   float64
 8   production_companies  4803 non-null   object
 9   release_date          4802 non-null   object
 10  revenue               4803 non-null   int64
 11  runtime               4801 non-null   float64
 12  spoken_languages      4803 non-null   object
 13  tagline               3959 non-null   object
 14  vote_average          4803 non-null   float64
 15  vote_count            4803 non-null   int64
 16  cast                  4803 non-null   object
dtypes: float64(3), int64(4), object(10)
memory usage: 638.0+ KB

In [135]:
movies.isnull().sum()

budget                    0
genres                    0
id                        0
keywords                  0
original_language         0
original_title            0
overview                  3
popularity                0
production_companies      0
release_date              1
revenue                   0
runtime                   2
spoken_languages          0
tagline                 844
vote_average              0
vote_count                0
cast                      0
dtype: int64

In [136]:
movies.dropna(inplace=True)

In [137]:
movies.iloc[0].genres

'[{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 878, "name": "Science Fiction"}]'

In [138]:
import ast
ast.literal_eval('[{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 878, "name": "Science Fiction"}]')

[{'id': 28, 'name': 'Action'},
 {'id': 12, 'name': 'Adventure'},
 {'id': 14, 'name': 'Fantasy'},
 {'id': 878, 'name': 'Science Fiction'}]

In [139]:
def convert(obj):
    L=[]
    counter=0
    for i in ast.literal_eval(obj):
        if counter!=3:
            L.append(i['name'])
            counter+=1
        else:
            break
        return L

In [140]:
movies['genres']=movies['genres'].apply(convert)

In [141]:
movies['keywords']=movies['keywords'].apply(convert)
movies['production_companies']=movies['production_companies'].apply(convert)
movies['spoken_languages']=movies['spoken_languages'].apply(convert)
movies['cast']=movies['cast'].apply(convert)

In [142]:
movies.head()

,budget,genres,id,keywords,original_language,original_title,overview,popularity,production_companies,release_date,revenue,runtime,spoken_languages,tagline,vote_average,vote_count,cast
0,237000000,[Action],19995,[culture clash],en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,[Ingenious Film Partners],2009-12-10,2787965087,162.0,[English],Enter the World of Pandora.,7.2,11800,[Sam Worthington]
1,300000000,[Adventure],285,[ocean],en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,[Walt Disney Pictures],2007-05-19,961000000,169.0,[English],"At the end of the world, the adventure begins.",6.9,4500,[Johnny Depp]
2,245000000,[Action],206647,[spy],en,Spectre,A cryptic message from Bondâ€™s past sends him o...,107.376788,[Columbia Pictures],2015-10-26,880674609,148.0,[FranÃ§ais],A Plan No One Escapes,6.3,4466,[Daniel Craig]
3,250000000,[Action],49026,[dc comics],en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,[Legendary Pictures],2012-07-16,1084939099,165.0,[English],The Legend Ends,7.6,9106,[Christian Bale]
4,260000000,[Action],49529,[based on novel],en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,[Walt Disney Pictures],2012-03-07,284139100,132.0,[English],"Lost in our world, found in another.",6.1,2124,[Taylor Kitsch]

In [143]:
movies['overview']=movies['overview'].apply(lambda x:x.split())

In [144]:
movies['tagline']=movies['tagline'].apply(lambda x:x.split())

In [145]:
movies.head()

,budget,genres,id,keywords,original_language,original_title,overview,popularity,production_companies,release_date,revenue,runtime,spoken_languages,tagline,vote_average,vote_count,cast
0,237000000,[Action],19995,[culture clash],en,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...",150.437577,[Ingenious Film Partners],2009-12-10,2787965087,162.0,[English],"[Enter, the, World, of, Pandora.]",7.2,11800,[Sam Worthington]
1,300000000,[Adventure],285,[ocean],en,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...",139.082615,[Walt Disney Pictures],2007-05-19,961000000,169.0,[English],"[At, the, end, of, the, world,, the, adventure...",6.9,4500,[Johnny Depp]
2,245000000,[Action],206647,[spy],en,Spectre,"[A, cryptic, message, from, Bondâ€™s, past, send...",107.376788,[Columbia Pictures],2015-10-26,880674609,148.0,[FranÃ§ais],"[A, Plan, No, One, Escapes]",6.3,4466,[Daniel Craig]
3,250000000,[Action],49026,[dc comics],en,The Dark Knight Rises,"[Following, the, death, of, District, Attorney...",112.312950,[Legendary Pictures],2012-07-16,1084939099,165.0,[English],"[The, Legend, Ends]",7.6,9106,[Christian Bale]
4,260000000,[Action],49529,[based on novel],en,John Carter,"[John, Carter, is, a, war-weary,, former, mili...",43.926995,[Walt Disney Pictures],2012-03-07,284139100,132.0,[English],"[Lost, in, our, world,, found, in, another.]",6.1,2124,[Taylor Kitsch]

In [146]:
movies['tags']=movies['overview']+movies['genres']+movies['keywords']+movies['cast']

In [147]:
movies.head()

,budget,genres,id,keywords,original_language,original_title,overview,popularity,production_companies,release_date,revenue,runtime,spoken_languages,tagline,vote_average,vote_count,cast,tags
0,237000000,[Action],19995,[culture clash],en,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...",150.437577,[Ingenious Film Partners],2009-12-10,2787965087,162.0,[English],"[Enter, the, World, of, Pandora.]",7.2,11800,[Sam Worthington],"[In, the, 22nd, century,, a, paraplegic, Marin..."
1,300000000,[Adventure],285,[ocean],en,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...",139.082615,[Walt Disney Pictures],2007-05-19,961000000,169.0,[English],"[At, the, end, of, the, world,, the, adventure...",6.9,4500,[Johnny Depp],"[Captain, Barbossa,, long, believed, to, be, d..."
2,245000000,[Action],206647,[spy],en,Spectre,"[A, cryptic, message, from, Bondâ€™s, past, send...",107.376788,[Columbia Pictures],2015-10-26,880674609,148.0,[FranÃ§ais],"[A, Plan, No, One, Escapes]",6.3,4466,[Daniel Craig],"[A, cryptic, message, from, Bondâ€™s, past, send..."
3,250000000,[Action],49026,[dc comics],en,The Dark Knight Rises,"[Following, the, death, of, District, Attorney...",112.312950,[Legendary Pictures],2012-07-16,1084939099,165.0,[English],"[The, Legend, Ends]",7.6,9106,[Christian Bale],"[Following, the, death, of, District, Attorney..."
4,260000000,[Action],49529,[based on novel],en,John Carter,"[John, Carter, is, a, war-weary,, former, mili...",43.926995,[Walt Disney Pictures],2012-03-07,284139100,132.0,[English],"[Lost, in, our, world,, found, in, another.]",6.1,2124,[Taylor Kitsch],"[John, Carter, is, a, war-weary,, former, mili..."

In [148]:
new_df=movies[['id','original_title','tags']]

In [149]:
new_df

,id,original_title,tags
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin..."
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d..."
2,206647,Spectre,"[A, cryptic, message, from, Bondâ€™s, past, send..."
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney..."
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili..."
...,...,...,...
4795,124606,Bang,"[A, young, woman, in, L.A., is, having, a, bad..."
4796,14337,Primer,"[Friends/fledgling, entrepreneurs, invent, a, ..."
4798,9367,El Mariachi,"[El, Mariachi, just, wants, to, play, his, gui..."
4799,72766,Newlyweds,NaN
4801,126186,Shanghai Calling,NaN

In [150]:
# Step 1: Inspect the Column
print(new_df['tags'].apply(type).unique())
non_iterable_elements = new_df['tags'][new_df['tags'].apply(lambda x: not isinstance(x, (list, tuple)))]
print(non_iterable_elements)

# Step 2: Convert to Iterables (if necessary)
new_df['tags'] = new_df['tags'].apply(lambda x: x if isinstance(x, (list, tuple)) else [x])

# Step 3: Apply the Join Function
new_df['tags'] = new_df['tags'].apply(lambda x: ",".join(map(str, x)))

# Display the DataFrame to verify the result
new_df.head()

[<class 'list'> <class 'float'>]
71      NaN
83      NaN
323     NaN
436     NaN
605     NaN
       ...
4760    NaN
4763    NaN
4764    NaN
4799    NaN
4801    NaN
Name: tags, Length: 201, dtype: object

C:\Users\hpw\AppData\Local\Temp\ipykernel_2968\740488794.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags'] = new_df['tags'].apply(lambda x: x if isinstance(x, (list, tuple)) else [x])
C:\Users\hpw\AppData\Local\Temp\ipykernel_2968\740488794.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags'] = new_df['tags'].apply(lambda x: ",".join(map(str, x)))

,id,original_title,tags
0,19995,Avatar,"In,the,22nd,century,,a,paraplegic,Marine,is,di..."
1,285,Pirates of the Caribbean: At World's End,"Captain,Barbossa,,long,believed,to,be,dead,,ha..."
2,206647,Spectre,"A,cryptic,message,from,Bondâ€™s,past,sends,him,o..."
3,49026,The Dark Knight Rises,"Following,the,death,of,District,Attorney,Harve..."
4,49529,John Carter,"John,Carter,is,a,war-weary,,former,military,ca..."

In [151]:
new_df['tags']=new_df['tags'].apply(lambda x: x.lower())

C:\Users\hpw\AppData\Local\Temp\ipykernel_2968\182503065.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags']=new_df['tags'].apply(lambda x: x.lower())

In [152]:
new_df.head()

,id,original_title,tags
0,19995,Avatar,"in,the,22nd,century,,a,paraplegic,marine,is,di..."
1,285,Pirates of the Caribbean: At World's End,"captain,barbossa,,long,believed,to,be,dead,,ha..."
2,206647,Spectre,"a,cryptic,message,from,bondâ€™s,past,sends,him,o..."
3,49026,The Dark Knight Rises,"following,the,death,of,district,attorney,harve..."
4,49529,John Carter,"john,carter,is,a,war-weary,,former,military,ca..."

In [153]:
import nltk

In [154]:
from nltk.stem.porter import PorterStemmer
ps=PorterStemmer()

In [155]:
def stem(text):
    y=[]
    for i in text.split():
        y.append(ps.stem(i))
        
    return " ".join(y)

In [156]:
new_df['tags']=new_df['tags'].apply(stem)

C:\Users\hpw\AppData\Local\Temp\ipykernel_2968\3514595201.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags']=new_df['tags'].apply(stem)

# Vactorisation of tags data so that convert text into a array matrics

In [157]:
from sklearn.feature_extraction.text import CountVectorizer
cv=CountVectorizer(max_features=5000, stop_words='english')

In [158]:
vectors=cv.fit_transform(new_df['tags']).toarray()

In [159]:
vectors[0]

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [160]:
cv.get_feature_names_out()

array(['000', '007', '10', ..., 'zone', 'zoo', 'zooey'], dtype=object)

# using cosine similarity

In [161]:
from sklearn.metrics.pairwise import cosine_similarity

In [162]:
similarity=cosine_similarity(vectors)

In [163]:
sorted(list(enumerate(similarity[1])),reverse=True,key=lambda x:x[1])[1:11]

[(11, 0.25),
 (340, 0.23570226039551587),
 (945, 0.2211629342323457),
 (1325, 0.2004459314343183),
 (16, 0.19062321291575585),
 (1051, 0.18569533817705186),
 (210, 0.18190171877724973),
 (2668, 0.18190171877724973),
 (3206, 0.18190171877724973),
 (101, 0.1767766952966369)]

In [164]:
def recommend(movies):
    movie_index=new_df[new_df['original_title']==movies].index[0]
    distance=similarity[movie_index]
    movies_list=sorted(list(enumerate(distance)),reverse=True,key=lambda x:x[1])[1:11]
    
    for i in movies_list:
        print(new_df.iloc[i[0]].original_title)
    return

In [165]:
recommend('Batman Begins')

The Matrix Reloaded
I Am Legend
City of Ember
Super Mario Bros.
The League of Extraordinary Gentlemen
Flyboys
Interstellar
Red Tails
The Matrix
The Good Dinosaur

In [166]:
new_df.iloc[303].original_title

'The Adventures of Pluto Nash'

In [167]:
import pickle

In [168]:
pickle.dump(new_df.to_dict(),open('movies.pkl','wb'))

In [169]:
pickle.dump(similarity,open('similarity.pkl','wb'))